//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_skip_ignored(SB), $0-24

    MOVQ doc+0(FP), DI
    MOVQ docLen+8(FP), SI
    MOVQ ret+16(FP), DX

    WORD $0x8b4c; BYTE $0x0a               // mov    r9, qword [rdx]
    WORD $0x8b4d; BYTE $0x11               // mov    r10, qword [r9]
    WORD $0x3949; BYTE $0xf2               // cmp    r10, rsi
    JAE  LBB0_10
    WORD $0x8b48; BYTE $0x3f               // mov    rdi, qword [rdi]
    QUAD $0x100100003e00b849; WORD $0x0000 // mov    r8, 17596481027584
    WORD $0x894c; BYTE $0xd2               // mov    rdx, r10

LBB0_2:
    LONG $0x170cb60f         // movzx    ecx, byte [rdi + rdx]
    LONG $0x2cf98348         // cmp    rcx, 44
    JA   LBB0_10
    LONG $0xc8a30f49         // bt    r8, rcx
    JAE  LBB0_5
    WORD $0x8948; BYTE $0xd1 // mov    rcx, rdx

LBB0_9:
    LONG $0x01c28349         // add    r10, 1
    WORD $0x894d; BYTE $0x11 // mov    qword [r9], r10
    LONG $0x01c18348         // add    rcx, 1
    WORD $0x8948; BYTE $0xca // mov    rdx, rcx
    WORD $0x3948; BYTE $0xf1 // cmp    rcx, rsi
    JB   LBB0_2
    JMP  LBB0_10

LBB0_5:
    LONG $0x23f98348 // cmp    rcx, 35
    JNE  LBB0_10

LBB0_6:
    LONG $0x014a8d48             // lea    rcx, [rdx + 1]
    LONG $0x01c28349             // add    r10, 1
    WORD $0x894d; BYTE $0x11     // mov    qword [r9], r10
    WORD $0x3948; BYTE $0xf1     // cmp    rcx, rsi
    JAE  LBB0_10
    LONG $0x1744b60f; BYTE $0x01 // movzx    eax, byte [rdi + rdx + 1]
    WORD $0x0d3c                 // cmp    al, 13
    JE   LBB0_9
    WORD $0x8948; BYTE $0xca     // mov    rdx, rcx
    WORD $0x0a3c                 // cmp    al, 10
    JNE  LBB0_6
    JMP  LBB0_9

LBB0_10:
    RET
